name: CI
on:
  push:
    branches: [ main ]
jobs:
  build_on_centos:
    runs-on: centos:latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: see  the direcory
        run: |
          cat /etc/os-release
          echo "this is the os"  
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: see  the direcory
        run: |
          cat /etc/os-release
          echo "this is the os"     
